repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args: [--maxkb=100000]
    -   id: check-docstring-first
    -   id: check-json
    -   id: no-commit-to-branch
    -   id: requirements-txt-fixer
-   repo: https://github.com/tconbeer/sqlfmt
    rev: v0.19.0
    hooks:
    -   id: sqlfmt
-   repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
    -   id: black
-   repo: local
    hooks:
    -   id: pytest-plots
        name: pytest-plots
        entry: pytest ./tests/pytest/plot_making_test.py
        language: system
        pass_filenames: false
        always_run: true
