sleep_android_viz:
  outputs:

    dev:
      type: sqlite
      threads: 1
      # Not used
      database: database
      schema: 'main'
      schemas_and_paths:
        main: 'database/final.db'
        raw: 'database/raw.db'
        staging: 'database/staging.db'
        intermediate: 'database/intermediate.db'

      schema_directory: '/database/'

  target: dev
